# Generated by Django 5.0.2 on 2024-03-01 03:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_fcc_api', '0002_administradores_alumnos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Maestros',
        ),
    ]
