# Generated by Django 5.0.2 on 2024-03-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_fcc_api', '0004_maestros_area_maestros_confirmar_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestros',
            name='curp',
        ),
    ]
