# Generated by Django 5.0.2 on 2024-04-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_fcc_api', '0005_remove_maestros_curp'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='confirmar_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='administradores',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='administradores',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='administradores',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='administradores',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maestros',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='materias_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
