# Generated by Django 5.0.2 on 2024-04-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_fcc_api', '0006_administradores_confirmar_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maestros',
            old_name='area',
            new_name='area_investigacion',
        ),
        migrations.RemoveField(
            model_name='administradores',
            name='confirmar_password',
        ),
        migrations.RemoveField(
            model_name='administradores',
            name='email',
        ),
        migrations.RemoveField(
            model_name='administradores',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='administradores',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='administradores',
            name='password',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='confirmar_password',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='email',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='password',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='confirmar_password',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='email',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='maestros',
            name='password',
        ),
        migrations.AddField(
            model_name='maestros',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
